Char1=input("enter any letter(small)")
Char2=input("enter same letter(CAPITAL)")
print('Letter\tASCII value')
print(Char1,'\t',ord(Char1))
print(Char2,'\t',ord(Char2))
print('Difference between ASCII values of two letters')
print(ord(Char1),'-',ord(Char2),'=',ends=' ')
print(ord(Char1)-ord(Char2))
